language: node_js
node_js:
- '16'
services:
- docker

notifications:
  email: false
  slack:
    rooms:
      secure: AY9ZKMEFie6OAgFuiaAKQsl62tC3cd7e+4L4GofgidJ9E7dBi6wiBlUCoSZ2aVLTGCNWhlxqGgk4Se4LFT1juJgVXklhGkiedW30Xau+zJpD64hmEdMtlssuSxiMY7MowZG8w2wSnwVnIL2T8yM9kjwT4ICxjZNFX05heYAIoQzW9Fv87aKK0mVGytmM7kkK228ApBH6ctcu8/Mw82AMVq2jaRIYg4BDxA3i512BtU9pdfUA2DNFtDlkPSZraPcKo+8dlRmYbyV3SOE2aAsZVG3aNp8EePciJZOuqWBgkHrA4UFcjVh31qgmAsq5rTQ3lEcESRPS6tQtDVOESa0igdOMzIseWizAJKiXvkr1aYqGD8as4/ccweRIauOg1zUixkP2ZBBnJ166cnfpSGW8XbYZEnnJ+bqruL9U+O4UDb97uOaI0dMhdXr66FgoegyKXeznrhoWzsv5guItcJbHY3Iz/GVtqLizPljiWR/560Fi1hK3G/jqXL0LQx3/nRNmeQ3ICigNZsDNQzbEDXkBH0OpktdqGdd5RK9ebrOum+Sszq59Bbt1EjHW9en8oWWuv4RZPsgVs+Dp8ubHMh/gztE+2Vefo3qtzvG8/VrpBcH72WyQutOEUWheoeABG2aWpsWSKQ+rqNSV5Rel+7/o1otCpbeibiAqGLnWPPdNOkc=
    on_success: always
    on_failure: always

before_script:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

script:
- |
  IMAGE_NAME="$TRAVIS_REPO_SLUG"
  if [[ -z "$TRAVIS_TAG" ]]; then
    IMAGE_TAG=latest
    KRAWLER_TAG=latest
  else
    IMAGE_TAG=$(node -p -e "require('./package.json').version")
    KRAWLER_TAG=$(node -p -e "require('./package.json').peerDependencies['@kalisio/krawler']")
  fi
  docker build --build-arg KRAWLER_TAG=$KRAWLER_TAG -f dockerfile.stations -t kalisio/k-awc:stations-${IMAGE_TAG} .  
  docker build --build-arg KRAWLER_TAG=$KRAWLER_TAG -f dockerfile.metar -t kalisio/k-awc:metar-${IMAGE_TAG} .

deploy:
  provider: script
  script: docker push kalisio/k-awc:stations-${IMAGE_TAG} && docker push kalisio/k-awc:metar-${IMAGE_TAG}
  on:
    all_branches: true
